### PR TITLE
Mission completed

### PR DESCRIPTION
**Pull request by ChennXIao**
http://3.105.22.12:3000/

謝謝老師

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Order id in thankyou page should be from query string, not localstorage.

**Comment by ChennXIao** [comment]
Modified.

http://3.105.22.12:3000/

謝謝老師

陳筱晴

**Review by cwpeng — CHANGES_REQUESTED** [review]
Clear booking data after successful ordering.

**Comment by ChennXIao** [comment]
Modified!!

http://3.105.22.12:3000/

謝謝老師

陳筱晴

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
