### PR TITLE
mission completed

### PR DESCRIPTION
**Pull request by ChennXIao**
陳筱晴

http://3.105.22.12:3000/
http://3.105.22.12:3000/attraction/2

謝謝老師

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your server.

**Comment by ChennXIao** [comment]
陳筱晴

http://3.105.22.12:3000/
http://3.105.22.12:3000/attraction/2

謝謝老師

**Comment by cwpeng** [comment]
Re-request review from top right corner in this pull request so that I can review for you.

**Comment by ChennXIao** [comment]
ok! I've clicked the Re-request review button

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Top separating line should extend to full width.
2. There is no space between navigator bar and image slider in mobile layout.

**Comment by ChennXIao** [comment]
已更正!

http://3.105.22.12:3000/
http://3.105.22.12:3000/attraction/2

陳筱晴

謝謝老師

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
